#!/usr/bin/env php
<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        $autoload = $file;
        break;
    }
}
unset($file);
require_once $autoload;

use Mleko\Wingman\Console\Application;

$app = new Application();

$app->run();
